name: Build image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v3
      - name: create tag
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/latex
          TAG=${IMAGE}:$(cat VERSION)-$(echo ${{ matrix.arch }} | tr -d '/')
          echo "IMAGE_TAGS=${TAG}" >> $GITHUB_ENV
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/${{ matrix.arch }}
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_TAGS }}
  manifest:
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: -1
      - name: create tag
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/latex
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo "IMAGE_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create multi-arch image manifest and GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=v$(cat VERSION)
          if git show-ref --tags | grep -q "refs/tags/${TAG}"
          then
            echo "${TAG} exists. Skipped"
            exit 0
          fi
          docker manifest create ${{ env.IMAGE }}:${IMAGE_VERSION} \
              ${{ env.IMAGE }}:${IMAGE_VERSION}-amd64 \
              ${{ env.IMAGE }}:${IMAGE_VERSION}-arm64
          docker manifest push ${{ env.IMAGE }}:${IMAGE_VERSION}
          docker manifest create ${{ env.IMAGE }}:latest \
              ${{ env.IMAGE }}:${IMAGE_VERSION}-amd64 \
              ${{ env.IMAGE }}:${IMAGE_VERSION}-arm64
          docker manifest push ${{ env.IMAGE }}:latest
          git tag ${TAG}
          git push --tags
          gh release create ${TAG} -n "${TAG}"


